using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using Vaktari.Core.FileSystem;

namespace Vaktari.Windows;

/// <summary>
/// Copy, move, delete and rename for Windows. Everything destructive routes
/// through here so there is exactly one place to get right.
///
/// <see cref="Trash"/> recycles, via SHFileOperation — see its own note for why
/// that P/Invoke rather than the modern COM IFileOperation.
///
/// **This header used to say ITrashMaintenance was still null**, so there was
/// no Trash view and no Restore and the bin could only be reached from
/// Explorer. WindowsTrashMaintenance shipped and made every word of that false,
/// and nobody came back to delete it — which is how Ctrl+Z after a delete stayed
/// broken here while working on Linux, with a comment explaining why it could
/// not possibly work.
///
/// **<see cref="Delete"/> is never a stand-in for <see cref="Trash"/>.** There
/// is no BCL API for the Recycle Bin, and the tempting shortcut when the
/// P/Invoke looks like work is to delete instead. Deleting a file the user
/// asked to be able to get back is not a degraded version of trashing it; it is
/// the one outcome the trash exists to prevent. When the recycle route refuses,
/// it reports a failure the UI can show, and the user still has their file.
/// </summary>
public sealed class WindowsFileOperations : IFileOperations
{
    private const int BufferSize = 1 << 20;

    private readonly ConcurrentStack<IUndoable> _undo = new();
    private readonly ConcurrentStack<IUndoable> _redo = new();

    public bool CanUndo => !_undo.IsEmpty;

    public IOperationHandle Copy(
        IReadOnlyList<string> sources, string destination,
        Func<FileConflict, ValueTask<ConflictResolution>> onConflict)
        => Run(sources, destination, onConflict, move: false);

    public IOperationHandle Move(
        IReadOnlyList<string> sources, string destination,
        Func<FileConflict, ValueTask<ConflictResolution>> onConflict)
        => Run(sources, destination, onConflict, move: true);

    /// <summary>
    /// Reads the bin, so a recycle can be undone.
    ///
    /// **Injected rather than constructed here** so the undo can be tested
    /// without recycling anything on the machine running the tests.
    /// </summary>
    internal ITrashMaintenance? Bin { get; init; }

    /// <summary>
    /// Stands in for the recycle itself.
    ///
    /// **So the tests do not fill the developer's Recycle Bin.** Everything
    /// worth testing here — which items the undo remembers, what happens when
    /// the bin cannot be read — is about the bookkeeping around
    /// SHFileOperation, not the call, and a test suite that genuinely recycles
    /// leaves litter on the machine that ran it.
    ///
    /// **It returns the shell's own answer rather than a bool.** The wording of
    /// a refusal, and the per-path re-run that names which file refused, are
    /// both decided from the status code, and neither is reachable from
    /// true/false.
    /// </summary>
    internal Func<IReadOnlyList<string>, RecycleResult>? RecycleOverride { get; init; }

    /// <summary>
    /// The Recycle Bin, via SHFileOperation.
    ///
    /// **SHFileOperation rather than IFileOperation**, which is the supported
    /// modern route and is COM. WINDOWS.md §6 warns that COM under NativeAOT is
    /// the risky combination and needs source-generated interop or it fails at
    /// runtime rather than at build time. This call is one struct and one
    /// function, source-generated by `LibraryImport` and AOT-clean today.
    /// IFileOperation buys progress and collision UI we do not use here, since
    /// <see cref="OperationHandle"/> already reports progress.
    ///
    /// **FOF_WANTNUKEWARNING is load-bearing, not decoration.** With
    /// FOF_ALLOWUNDO alone, a file too large for the bin — or any file when the
    /// bin is disabled for that drive — is *permanently deleted*, silently,
    /// because FOF_NOCONFIRMATION suppressed the question Explorer would have
    /// asked. WANTNUKEWARNING partially overrides NOCONFIRMATION for exactly
    /// that case: ordinary recycling stays silent, and destruction still has to
    /// be agreed to. Removing it turns this method into <see cref="Delete"/>
    /// without saying so.
    /// </summary>
    /// <summary>
    /// One call to the shell, owning the memory it marshals.
    ///
    /// Extracted because the refusal path calls it AGAIN, once per path, to
    /// learn which file the single status code was about — and one finally at
    /// the top of Trash could only ever free the first allocation.
    /// </summary>
    private static RecycleResult Recycle(IReadOnlyList<string> full)
    {
        var from = Native.DoubleNullTerminated(full);

        try
        {
            var operation = new Native.SHFILEOPSTRUCTW
            {
                wFunc = Native.FO_DELETE,
                pFrom = from,
                fFlags = Native.FOF_ALLOWUNDO
                       | Native.FOF_NOCONFIRMATION
                       | Native.FOF_WANTNUKEWARNING
                       | Native.FOF_SILENT
                       | Native.FOF_NOERRORUI,
            };

            var status = Native.SHFileOperation(ref operation);

            return new RecycleResult(status, operation.fAnyOperationsAborted != 0);
        }
        finally
        {
            Marshal.FreeHGlobal(from);
        }
    }

    /// <summary>
    /// Records whatever reached the bin, so it can be taken back out.
    ///
    /// **A refusal used to return before this.** A batch that stumbled on its
    /// last file lost the undo for every file ahead of it, which is precisely
    /// the moment somebody reaches for Ctrl+Z. Wrapped so that no exit from
    /// Trash can skip it by forgetting to repeat two lines.
    /// </summary>
    private void RememberArrivals(
        ITrashMaintenance? bin, HashSet<string>? before, IReadOnlyList<string> asked)
    {
        var landed = Arrivals(bin, before);

        // The names the person used, carried alongside the trash keys. A key
        // here is a $I metadata path, which is not something to put in a menu
        // row — and the undo has to be described from the outside anyway.
        if (landed.Count > 0) Remember(new UndoTrash(bin!, landed, asked));
    }

    public IOperationHandle Trash(IReadOnlyList<string> paths)
    {
        var handle = new OperationHandle();

        _ = Task.Run(() =>
        {
            // **Noted before the recycle, so the undo can find what moved.**
            // SHFileOperation reports nothing about what it recycled, which is
            // why this was undoable on Linux and not here. The bin knows,
            // though: a recycled item appears in the listing with the path it
            // came from, so the difference between the listing before and after
            // names exactly what just went in.
            var bin = Bin;
            var before = Snapshot(bin);

            try
            {
                handle.Begin(paths.Count, totalBytes: 0);

                // SHFileOperation wants absolute paths — a relative one is
                // resolved against the process working directory, which is not
                // the folder being listed.
                // Same stripping, and the shell is no better at it: the path
                // reaching SHFileOperation has already lost the trailing
                // character, so the bin would swallow the neighbouring file.
                // GetFullPath itself is where it happens, which is why the
                // check comes first.
                foreach (var path in paths)
                    if (ReachablePath.Refuse(path) is { } unreachable)
                    {
                        handle.Failed(new IOException(unreachable));
                        return;
                    }

                var full = paths.Select(Path.GetFullPath).ToList();

                RecycleResult Attempt(IReadOnlyList<string> some)
                    => RecycleOverride is { } fake ? fake(some) : Recycle(some);

                var outcome = Attempt(full);

                // Aborted covers the user declining the warning about a file too
                // big for the bin, which is a cancellation rather than a failure.
                if (outcome.Aborted)
                {
                    // **What did go still has to be undoable.** The bin may
                    // already hold everything but the one file the warning was
                    // about, and returning here left all of them with no way
                    // back.
                    RememberArrivals(bin, before, paths);
                    handle.Cancelled();
                    return;
                }

                if (outcome.Status == 0)
                {
                    // One SHFileOperation covers the whole batch, so there is no
                    // per-item progress along the way — but the count the handle
                    // was opened with still has to be reached, or trashing three
                    // files finishes reading "1/3".
                    for (var i = 0; i < full.Count; i++) handle.ItemFinished();
                }
                else if (full.Count == 1)
                {
                    handle.ItemFailed(full[0], RecycleRefusal.For(outcome.Status));
                }
                else
                {
                    // **One number for a whole batch names nothing.** The shell
                    // reports a single int for however many paths it was given,
                    // so a file held open by another program produced
                    // "SHFileOperation returned 32" and left the person to work
                    // out which of their twenty files it was. Asked one at a
                    // time, it answers one at a time.
                    foreach (var one in full)
                    {
                        // Skipped, not re-asked: the batch call may have
                        // recycled several before it refused, and asking again
                        // would answer "not there any more" — a success
                        // reported as a failure.
                        if (!File.Exists(one) && !Directory.Exists(one))
                        {
                            handle.ItemFinished();
                            continue;
                        }

                        var each = Attempt([one]);

                        if (each.Aborted) handle.ItemFailed(one, new OperationCanceledException());
                        else if (each.Status != 0) handle.ItemFailed(one, RecycleRefusal.For(each.Status));
                        else handle.ItemFinished();
                    }
                }

                RememberArrivals(bin, before, paths);

                // Completed with Problems rather than Failed: the ones that went
                // really did go, and the status line reports what was left
                // behind. Delete and the Linux engine already do this.
                handle.Complete();
            }
            catch (Exception ex)
            {
                handle.Failed(ex);
            }
        });

        return handle;
    }

    /// <summary>
    /// The trash names currently in the bin, or null when there is no bin to
    /// ask — which is how the undo stays absent rather than wrong.
    /// </summary>
    private static HashSet<string>? Snapshot(ITrashMaintenance? bin)
    {
        if (bin is null) return null;

        try
        {
            return bin.List().Select(item => item.TrashName).ToHashSet(StringComparer.Ordinal);
        }
        catch (Exception ex)
        {
            // A bin that will not answer means no undo entry, never a failed
            // delete: the files really did go where the user asked.
            Vaktari.Core.Quiet.Swallowed("file-ops", ex);
            return null;
        }
    }

    /// <summary>
    /// What appeared in the bin since the snapshot.
    ///
    /// **By difference, not by matching original paths.** Matching on where an
    /// item came from picks the wrong entry when the same name has been deleted
    /// before — and deleting, restoring and deleting again is exactly when
    /// somebody reaches for undo. A trash name is unique and new ones can only
    /// be what just arrived.
    /// </summary>
    private static List<string> Arrivals(ITrashMaintenance? bin, HashSet<string>? before)
    {
        if (bin is null || before is null) return [];

        try
        {
            return bin.List()
                .Select(item => item.TrashName)
                .Where(name => !before.Contains(name))
                .ToList();
        }
        catch (Exception ex)
        {
            Vaktari.Core.Quiet.Swallowed("file-ops", ex);
            return [];
        }
    }

    /// <summary>
    /// Puts recycled items back where they came from.
    ///
    /// **This was impossible until the bin could be read.** The comment that
    /// stood here said restoring needed a COM decision that was still
    /// outstanding — WindowsTrashMaintenance shipped and made that false, and
    /// nothing came back to remove the claim. So Ctrl+Z after a delete did
    /// nothing on Windows while working on Linux, with no sign of why.
    /// </summary>
    private sealed class UndoTrash(
        ITrashMaintenance bin,
        List<string> trashNames,
        IReadOnlyList<string> originals) : IUndoable
    {
        public string Describe => UndoNames.Of("delete", originals);

        public ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            foreach (var name in trashNames)
            {
                ct.ThrowIfCancellationRequested();

                try
                {
                    bin.Restore(name);
                }
                catch (Exception ex)
                {
                    // One item that will not come back must not strand the
                    // rest — the same rule the copy engine now follows.
                    Vaktari.Core.Quiet.Swallowed("file-ops", ex);
                }
            }

            // No redo: putting them back in the bin would need the paths they
            // were restored to, and Restore reports where each one went. That
            // is the next increment, not a guess made here.
            return ValueTask.FromResult<IUndoable?>(null);
        }
    }

    /// <summary>
    /// Irreversible. Only ever reached from an explicit, separate user action —
    /// never as the default for the Delete key.
    /// </summary>
    public IOperationHandle Delete(IReadOnlyList<string> paths)
    {
        var handle = new OperationHandle();

        _ = Task.Run(async () =>
        {
            try
            {
                handle.Begin(paths.Count, totalBytes: 0);

                // A delete has no target to carry: the item's own path is where
                // the retry goes again, and there is no conflict machinery to
                // land in.
                var failed = new List<RetryRoot>();

                foreach (var path in paths)
                {
                    handle.Token.ThrowIfCancellationRequested();
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);

                    handle.ItemStarted(path);

                    // **The wrong file, silently.** A name ending in a space or
                    // a dot is stripped by the path layer before the call, so
                    // deleting "report " deletes "report" and leaves "report "
                    // standing. Refused per item rather than for the whole
                    // batch: the other twenty files the user selected are fine
                    // and should still go.
                    if (ReachablePath.Refuse(path) is { } unreachable)
                    {
                        handle.ItemFailed(path, new IOException(unreachable));
                        continue;
                    }

                    // A read-only file refuses to delete on Windows where it
                    // would go on Linux, because the permission is on the file
                    // rather than its directory. The user asked for it to go.
                    //
                    // The whole tree, not just its root: Directory.Delete stops
                    // at the first read-only file inside and throws, leaving
                    // half of what the user asked to remove standing. One
                    // cloned repository is enough to hit that — git writes its
                    // pack files read-only.
                    ClearReadOnlyTree(path);

                    // **Per item, the way the copy engine already does it.**
                    // One try wrapped the whole loop, so a single file open in
                    // another program abandoned every remaining item in the
                    // selection — and the message named the exception rather
                    // than the file, so nobody could tell which one stopped it
                    // or what had already gone.
                    try
                    {
                        if (Directory.Exists(path)) Directory.Delete(path, recursive: true);
                        else File.Delete(path);

                        handle.ItemFinished();
                    }
                    catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                    {
                        handle.ItemFailed(path, ex);

                        failed.Add(new RetryRoot(path, path, Directory.Exists(path)));
                    }
                }

                // Before Complete, so a cancelled run offers nothing.
                if (RetryRoots.Outermost(failed) is { Count: > 0 } worthRetrying)
                    handle.Retry = new RetryOffer(
                        worthRetrying.Count,
                        () => Delete([.. worthRetrying.Select(r => r.Source)]));

                handle.Complete();
            }
            catch (OperationCanceledException) { handle.Cancelled(); }
            catch (Exception ex) { handle.Failed(ex); }
        });

        return handle;
    }

    private static void ClearReadOnly(string path)
    {
        try
        {
            var attributes = File.GetAttributes(path);
            if ((attributes & FileAttributes.ReadOnly) != 0)
                File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            // Let the delete itself report the problem.
        }
    }

    /// <summary>
    /// The same, for everything a recursive delete is about to touch. Reparse
    /// points are cleared but not descended through, for the reason
    /// <see cref="Descend"/> gives — and the delete removes the link rather
    /// than what is behind it, so what is behind it is not its business.
    /// </summary>
    /// <summary>
    /// Internal so the Recycle Bin's own purge uses this rather than growing a
    /// second copy. One rule in one place: a duplicate that drifts is how the
    /// bin came to half-destroy read-only payloads while this path handled them
    /// correctly.
    /// </summary>
    internal static void ClearReadOnlyTree(string path)
    {
        ClearReadOnly(path);

        if (!Directory.Exists(path) || IsLink(path)) return;

        foreach (var (entry, _, _) in Descend(path, CancellationToken.None))
            ClearReadOnly(entry);
    }

    public ValueTask RenameAsync(string path, string newName, CancellationToken ct)
    {
        // **Every character Windows refuses, not just the separators.** A
        // colon used to reach the filesystem and come back as the raw "The
        // parameter is incorrect."; worse, "d:notes" is drive-RELATIVE, so
        // Path.Combine discarded the folder and the file silently left the
        // listing for the current directory of drive D:.
        if (FileNames.Refuse(newName) is { } why)
            throw new ArgumentException(why, nameof(newName));

        // The name being renamed FROM matters more than the one typed: a
        // trailing space on the existing name means File.Move would rename the
        // neighbour instead, and the row that was clicked would sit there
        // apparently untouched.
        if (ReachablePath.Refuse(path) is { } unreachable)
            throw new IOException(unreachable);

        var directory = PathRules.Parent(Path.GetFullPath(path))
            ?? throw new IOException("A drive root cannot be renamed.");

        var target = Path.Combine(directory, newName);

        // Ordinal, deliberately, where the rest of this file compares paths with
        // PathRules.Same. Same is case-insensitive on Windows, so it calls
        // "readme.txt" and "README.txt" one name and returns here without
        // renaming anything — silently swallowing the exact correction the
        // check below is written to let through.
        if (string.Equals(target, path, StringComparison.Ordinal))
            return ValueTask.CompletedTask;

        // Case-insensitively, so renaming "readme" to "README" is not rejected
        // as already existing — it is the same file, and the rename is exactly
        // how a user fixes the case of a name.
        if ((File.Exists(target) || Directory.Exists(target))
            && !string.Equals(target, path, StringComparison.OrdinalIgnoreCase))
            throw new IOException($"'{newName}' already exists here.");

        if (Directory.Exists(path)) RenameDirectory(path, target);
        else File.Move(path, target, overwrite: false);

        // Before the undo entry, so a rename that is immediately undone leaves
        // the index where it started rather than one step behind.

        Remember(new UndoRename(target, path));
        return ValueTask.CompletedTask;
    }

    /// <summary>
    /// Directory.Move, plus the case-only rename it will not do.
    ///
    /// It compares its two paths case-insensitively on Windows and throws
    /// "source and destination path must be different" when they match, so
    /// fixing the case of a folder name has to go through a staging name — the
    /// two-step Explorer performs on your behalf. Files need none of this:
    /// File.Move hands the pair straight to MoveFileEx, which renames in place.
    /// </summary>
    private static void RenameDirectory(string from, string to)
    {
        if (!string.Equals(from, to, StringComparison.OrdinalIgnoreCase))
        {
            Directory.Move(from, to);
            return;
        }

        var parent = PathRules.Parent(to)
            ?? throw new IOException("A drive root cannot be renamed.");

        string staging;
        do
        {
            staging = Path.Combine(parent, $".vaktari-rename-{Guid.NewGuid():N}");
        }
        while (Directory.Exists(staging) || File.Exists(staging));

        Directory.Move(from, staging);

        try
        {
            Directory.Move(staging, to);
        }
        catch
        {
            // Never leave the folder sitting under the staging name: the user
            // would be looking for it by either of the two names they know.
            Directory.Move(staging, from);
            throw;
        }
    }

    /// <summary>
    /// Records something new, and abandons the redo history.
    ///
    /// **Every application with an undo does this.** Once the history has been
    /// departed from, a redo would apply to a state that no longer exists — it
    /// would move a file that has since been renamed, or put back something
    /// that was overwritten in the meantime.
    /// </summary>
    public void RecordCreation(string path)
    {
        if (path.Length > 0) Remember(new UndoCreate(Trash, path));
    }

    private void Remember(IUndoable action)
    {
        _redo.Clear();
        _undo.Push(action);
    }

    public bool CanRedo => !_redo.IsEmpty;

    // Peeked rather than popped, and read on every ask: the menu row is built
    // when the menu opens and the status line is written after the work, so
    // both want the answer as it is now.
    public string? UndoDescription => _undo.TryPeek(out var next) ? next.Describe : null;

    public string? RedoDescription => _redo.TryPeek(out var next) ? next.Describe : null;

    /// <summary>
    /// Puts back what an undo took away.
    ///
    /// The stack is emptied by any new operation, which is what every
    /// application with an undo does: once the history has been departed from,
    /// a redo would apply to a state that no longer exists.
    /// </summary>
    public async ValueTask RedoAsync(CancellationToken ct)
    {
        if (!_redo.TryPop(out var action)) return;

        if (await action.UndoAsync(ct).ConfigureAwait(false) is { } undo) _undo.Push(undo);
    }

    public async ValueTask UndoAsync(CancellationToken ct)
    {
        if (_undo.TryPop(out var action)
            && await action.UndoAsync(ct).ConfigureAwait(false) is { } redo)
            _redo.Push(redo);
    }

    /// <summary>
    /// <paramref name="retrying"/> is the second pass: the items a previous run
    /// could not do, each back to the place THAT run decided to put it.
    ///
    /// **The targets are carried rather than recomputed**, because "sources into
    /// destination" no longer says where anything goes once a Keep both has
    /// renamed the root or a duplicate in place has given it a " - Copy" name.
    /// Recomputing would put the retried items into the folder the user asked to
    /// keep separate — which is the documented fault the redirect map exists to
    /// prevent, arriving a second time by a different road.
    /// </summary>
    private IOperationHandle Run(
        IReadOnlyList<string> sources, string destination,
        Func<FileConflict, ValueTask<ConflictResolution>> onConflict, bool move,
        IReadOnlyList<RetryRoot>? retrying = null)
    {
        var handle = new OperationHandle();

        _ = Task.Run(async () =>
        {
            try
            {
                // Enumerating first means the progress bar is honest from the
                // start rather than discovering the total as it goes.
                // **Checked before the plan is built**, and for the whole
                // operation rather than per item. A copy reads the source by
                // name and writes the target by name; with a trailing space at
                // either end the read would come from the neighbouring file and
                // a move would then delete a source that was never copied. The
                // destination counts too — a folder called "work " is a
                // different folder to Windows than the one on screen.
                //
                // Skipped on a retry: these same paths were accepted by the run
                // that produced the failures, and a retry adds no new ones.
                if (retrying is null)
                    foreach (var path in sources.Append(destination))
                        if (ReachablePath.Refuse(path) is { } unreachable)
                        {
                            handle.Failed(new IOException(unreachable));
                            return;
                        }


                // **A folder cannot be copied or moved into itself.** Neither
                // into itself nor into one of its own subfolders: the plan is
                // built by walking the source, and the destination is inside
                // what is being walked, so a copy feeds itself and a MOVE
                // dismantles the tree it is halfway through reading. Explorer
                // and Dolphin both refuse outright.
                //
                // This also covers dropping a selection onto a folder that is
                // part of that selection — the destination IS one of the
                // sources — which a six-pixel twitch over a selected folder was
                // enough to start.
                //
                // Checked here rather than at each caller so every route is
                // covered at once: Ctrl+V, Copy to, Move to and a drop.
                // Deduplicating into the PARENT is untouched, which is what
                // makes Duplicate still work.
                //
                // Also skipped on a retry, and for the same reason: the shape
                // of the operation was settled by the run that failed.
                foreach (var source in retrying is null ? sources : [])
                {
                    if (!Directory.Exists(source)) continue;
                    if (!PathRules.Contains(source, destination)) continue;

                    var name = PathRules.LeafName(source);

                    handle.Failed(new IOException(
                        PathRules.Same(source, destination)
                            ? $"\"{name}\" cannot be copied into itself."
                            : $"\"{name}\" cannot be copied into a folder inside it."));

                    return;
                }

                var unreadable = new List<(string Path, Exception Error)>();

                // What a retry would go again on. Fed ONLY by the per-item
                // catch, deliberately: a folder the plan could not read is
                // recorded before the redirect map exists, so its target is the
                // pre-conflict guess — and re-attempting it after a Keep both
                // would merge the subtree into the folder the user asked to
                // keep separate. That is the fault the redirect map was written
                // to prevent, and an unreadable folder is the case a retry
                // least often fixes anyway.
                var failed = new List<RetryRoot>();

                // On the first pass a root goes to destination + its own name;
                // on a retry it goes back to wherever the failed run decided.
                var roots = retrying is { } again
                    ? again.Select(r => (r.Source, r.Target)).ToList()
                    : sources.Select(source =>
                      {
                          var full = Path.GetFullPath(source);

                          return (full, Path.Combine(destination, PathRules.LeafName(full)));
                      }).ToList();

                var plan = BuildPlan(roots, handle.Token, unreadable);

                // **Asked before a byte moves.** A fifty-gigabyte copy onto a
                // drive with room for thirty filled the disk and then failed
                // somewhere in the middle, leaving a part-written tree and a
                // machine with nothing left. Explorer refuses up front and says
                // how much short it is.
                //
                // A move within one volume is exempt: it is a rename and needs
                // no space at all.
                // Asked on a retry too, over the retry's own plan. A retry is
                // NOT a strict subset of what was measured: nothing under a
                // folder that could not be read was ever counted, so a second
                // pass that finally reads it can be arbitrarily large.
                if (!move || !SameVolume([.. roots.Select(r => r.Item1)], destination))
                {
                    var needed = plan.Sum(p => p.Length);

                    if (FreeSpaceOn(destination) is { } free && needed > free)
                    {
                        handle.Failed(new IOException(
                            $"there is not enough room on {PathRules.LeafName(destination)}: "
                            + $"{ByteSize.Format(needed)} needed, {ByteSize.Format(free)} free"));

                        return;
                    }
                }

                handle.Begin(plan.Count, plan.Sum(p => p.Length));

                // Reported before anything is copied: these are folders the
                // plan could not see into, so nothing beneath them will be
                // attempted and the person should know which.
                foreach (var (path, error) in unreadable) handle.ItemFailed(path, error);

                // A folder resolved with KeepBoth lands under a name the plan
                // did not know about, and every item beneath it was planned
                // against the old one. Without carrying the change down, the
                // new folder is created empty while the tree merges into the
                // one the user asked to keep separate — which on a move is the
                // source disappearing into it.
                var redirects = new List<(string From, string To)>();

                // Where each top-level source actually ended up, and what was
                // left behind. The undo used to reconstruct the landing site as
                // destination + name, which is only true when nothing was
                // deduplicated or skipped.
                var landings = new List<(string Source, string Target)>();
                var skipped = new List<(string Source, string Target)>();

                // Targets of folders the user chose to skip. Everything planned
                // underneath one of them is skipped too.
                var skippedRoots = new List<string>();

                foreach (var item in plan)
                {
                    handle.Token.ThrowIfCancellationRequested();
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);

                    var target = Redirect(item.Target, redirects);

                    // Under a folder that was skipped: skip it too, before the
                    // conflict prompt can ask about it a second time.
                    if (Under(target, skippedRoots))
                    {
                        handle.ItemFinished();
                        continue;
                    }

                    // **Pasting into the folder it already lives in.** The
                    // target then IS the source, so the conflict prompt could
                    // only offer to replace a file with itself — and Replace
                    // cannot work, because the copy opens the same path for
                    // reading and writing and the error blames "something else
                    // has that file open". Explorer makes a duplicate, which is
                    // plainly what was meant; a MOVE to where it already is has
                    // nothing to do at all.
                    if (PathRules.Same(item.Source, target))
                    {
                        if (move)
                        {
                            handle.ItemFinished();
                            continue;
                        }

                        // **The rename has to travel down.** Every descendant
                        // was planned against the original name, and without a
                        // redirect each one hit this same branch and was
                        // deduplicated where it stood -- so duplicating a
                        // folder produced an empty "A - Copy" and littered the
                        // ORIGINAL with "x - Copy" twins of every file inside
                        // it, reported as success. The KeepBoth branch below
                        // has always recorded one.
                        // In place: this is the duplicate branch, where the
                        // target IS the source, so " - Copy" is the truth.
                        var deduped = Deduplicate(
                            target, item.Kind == ItemKind.Directory, inPlace: true);

                        if (item.Kind == ItemKind.Directory) redirects.Add((target, deduped));

                        target = deduped;
                    }

                    if (File.Exists(target) || Directory.Exists(target))
                    {
                        switch (await onConflict(new FileConflict(item.Source, target)).ConfigureAwait(false))
                        {
                            case ConflictResolution.Skip:
                                // **The whole subtree, not just this entry.**
                                // Skipping a folder skipped only the folder
                                // itself: every file planned inside it still
                                // went into the existing folder -- a merge
                                // nobody asked for -- and on a move the source
                                // folder was then deleted as "empty". Skip in
                                // both references leaves the folder untouched
                                // at both ends.
                                skipped.Add((item.Source, target));

                                if (item.Kind == ItemKind.Directory)
                                    skippedRoots.Add(target);

                                handle.ItemFinished();
                                continue;
                            case ConflictResolution.KeepBoth:
                                // A conflict in ANOTHER folder. Nothing here
                                // is a copy of anything the user can see, so
                                // this arrives as "(2)" rather than claiming a
                                // provenance it does not have.
                                var kept = Deduplicate(
                                    target, item.Kind == ItemKind.Directory, inPlace: false);
                                if (item.Kind == ItemKind.Directory)
                                    redirects.Add((target, kept));
                                target = kept;
                                break;
                            case ConflictResolution.Cancel:
                                throw new OperationCanceledException();
                            case ConflictResolution.Overwrite:
                                break;
                        }
                    }

                    handle.ItemStarted(item.Source);

                    // **One item's failure is not the batch's.** This whole
                    // block used to sit inside a single try around the entire
                    // loop, so copying twelve files with the third open in
                    // another program copied two and abandoned nine — and said
                    // neither which file nor what was left undone. Cancellation
                    // still ends everything, because that is what was asked for.
                    try
                    {
                    Directory.CreateDirectory(PathRules.Parent(target) ?? destination);

                    switch (item.Kind)
                    {
                        case ItemKind.Directory:
                            Directory.CreateDirectory(target);
                            break;

                        case ItemKind.Link:
                            CopyLink(item.Source, target);
                            if (move) DeleteLink(item.Source);
                            break;

                        default:
                            // **A move within one volume is a rename.** Copying
                            // every byte and deleting the original is correct
                            // and ruinously slow: moving a folder of video
                            // inside one drive rewrote the whole folder. The
                            // giveaway that the trick was already known is that
                            // UNDOING a move has always used File.Move, so the
                            // undo of a fifty-gigabyte move was instant while
                            // the move itself was not.
                            if (CanRename(item.Source, target, move))
                            {
                                // The target only exists here if the user chose
                                // to overwrite it; Skip continued, and KeepBoth
                                // already moved the name aside.
                                if (File.Exists(target)) ClearReadOnly(target);

                                File.Move(item.Source, target, overwrite: true);

                                // Reported so the bar still advances: a rename
                                // moves the bytes without reading any, and a
                                // progress bar that sits at zero through the
                                // fast path looks like a hang.
                                handle.BytesCopied(item.Length);
                            }
                            else
                            {
                                await CopyFileAsync(item.Source, target, handle)
                                    .ConfigureAwait(false);

                                if (move)
                                {
                                    ClearReadOnly(item.Source);
                                    File.Delete(item.Source);
                                }
                            }
                            break;
                    }

                    if (item.IsRoot) landings.Add((item.Source, target));
                    }
                    catch (OperationCanceledException)
                    {
                        // Cancelling means stop, so this one does leave the loop.
                        throw;
                    }
                    catch (Exception ex)
                    {
                        // Recorded and carried on. A directory that could not be
                        // created also means its contents will fail, and each of
                        // those is reported on its own — noisy, but honest, and
                        // far better than nine files silently not arriving.
                        handle.ItemFailed(item.Source, ex);

                        // The post-redirect target, which is the whole reason
                        // the recipe carries one.
                        failed.Add(new RetryRoot(
                            item.Source, target, item.Kind == ItemKind.Directory));
                    }

                    handle.ItemFinished();
                }

                // Directories are removed only after their contents moved, so a
                // cancelled move never deletes a folder it has not emptied.
                // Every directory the plan touched, deepest first — checking
                // the top-level sources alone left the whole skeleton standing,
                // because a root is never empty while its own subdirectories
                // are still in it.
                if (move)
                {
                    foreach (var directory in plan
                                 .Where(i => i.Kind == ItemKind.Directory)
                                 .Select(i => i.Source)
                                 .Reverse())
                        if (Directory.Exists(directory)
                            && !Directory.EnumerateFileSystemEntries(directory).Any())
                            Directory.Delete(directory);
                }

                if (landings.Count == 0)
                {
                    // nothing landed, nothing to take back
                }
                else if (move)
                {
                    Remember(new UndoMove(landings));
                }
                else
                {
                    // **Undoable now, into the bin.** The old note here said a
                    // copy could not be undone because undoing one means
                    // deleting files. True, and the bin is the answer: nothing
                    // is destroyed, and pasting into the wrong folder stops
                    // being a mistake you have to clean up by hand.
                    Remember(new UndoCopy(Trash, landings.Select(l => l.Target).ToList()));
                }


                // **Set immediately before Complete**, so a cancelled or failed run
                // leaves it null: somebody who pressed cancel is not asking to be
                // offered the same work back. The closure carries the SAME conflict
                // callback, so an "apply to the rest" already answered is not asked
                // again.
                if (RetryRoots.Outermost(failed) is { Count: > 0 } worthRetrying)
                    handle.Retry = new RetryOffer(
                        worthRetrying.Count,
                        () => Run(sources, destination, onConflict, move, worthRetrying));

                handle.Complete();
            }
            catch (OperationCanceledException) { handle.Cancelled(); }
            catch (Exception ex) { handle.Failed(ex); }
        });

        return handle;
    }

    /// <summary>
    /// **Windows' convention, not freedesktop's.** XdgTrash.Deduplicate produces
    /// "file (1).txt"; Explorer produces "file - Copy.txt" and then
    /// "file - Copy (2).txt". WINDOWS.md flagged this as the one place a
    /// platform helper was misleadingly named — the rule differs, so the code
    /// does too rather than being shared.
    /// </summary>
    /// <summary>
    /// A free name beside <paramref name="target"/>.
    ///
    /// **One naming served two different questions, and only one of them is
    /// about copying.** Keeping both across a MOVE named the arrival
    /// "report - Copy.txt" — after an operation that copied nothing and left
    /// nothing behind, in a folder where no "report.txt" of yours had ever
    /// been. The word was describing the mechanism rather than what happened.
    ///
    /// Explorer splits them and this now does too: " - Copy" is what a
    /// duplicate IN PLACE is called, because there the word is true and the two
    /// files really are one beside its copy; a conflict resolved by keeping
    /// both is "(2)", which says only that this is the second thing here
    /// wanting that name.
    ///
    /// No default. A third caller has to say which of the two it is, because
    /// getting it wrong is silent and only shows up in a filename somebody
    /// reads a week later.
    ///
    /// The kind matters: see PathRules.SplitLeaf for why a folder — and a
    /// dotfile — is atomic.
    /// </summary>
    internal static string Deduplicate(string target, bool isDirectory, bool inPlace)
    {
        var directory = PathRules.Parent(target);
        if (directory is null) return target;

        var (stem, extension) = PathRules.SplitLeaf(PathRules.LeafName(target), isDirectory);

        if (inPlace)
        {
            var copy = Path.Combine(directory, $"{stem} - Copy{extension}");

            for (var n = 2; File.Exists(copy) || Directory.Exists(copy); n++)
                copy = Path.Combine(directory, $"{stem} - Copy ({n}){extension}");

            return copy;
        }

        // From two, because the thing already sitting there is the first.
        var arrival = Path.Combine(directory, $"{stem} (2){extension}");

        for (var n = 3; File.Exists(arrival) || Directory.Exists(arrival); n++)
            arrival = Path.Combine(directory, $"{stem} ({n}){extension}");

        return arrival;
    }

    /// <summary>
    /// Carries a renamed ancestor down to the descendants planned against its
    /// old name. Applied in order, so a redirect recorded later is already
    /// expressed in terms of the ones before it and nesting composes.
    /// </summary>
    private static string Redirect(string target, List<(string From, string To)> redirects)
    {
        foreach (var (from, to) in redirects)
        {
            if (string.Equals(target, from, PathRules.Comparison)) return to;

            var prefix = from + Path.DirectorySeparatorChar;
            if (target.StartsWith(prefix, PathRules.Comparison))
                target = to + target[from.Length..];
        }

        return target;
    }

    /// <summary>
    /// Whether a planned target sits at or beneath one of these roots. The same
    /// prefix rule <see cref="Redirect"/> uses: the separator is part of the
    /// test, so "work 2" is not treated as living inside "work".
    /// </summary>
    private static bool Under(string target, List<string> roots)
    {
        foreach (var root in roots)
        {
            if (string.Equals(target, root, PathRules.Comparison)) return true;

            if (target.StartsWith(root + Path.DirectorySeparatorChar, PathRules.Comparison))
                return true;
        }

        return false;
    }

    /// <summary>
    /// What is left on the volume a path lives on, or null when it cannot be
    /// asked — a network share often cannot, and refusing a copy because the
    /// question failed would be worse than trying it.
    /// </summary>
    private static long? FreeSpaceOn(string path)
    {
        try
        {
            var root = Path.GetPathRoot(Path.GetFullPath(path));

            return root is { Length: > 0 } ? new DriveInfo(root).AvailableFreeSpace : null;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException
                                      or ArgumentException or NotSupportedException)
        {
            return null;
        }
    }

    /// <summary>Whether every source is on the same volume as the destination,
    /// in which case a move is a rename and costs no space.</summary>
    private static bool SameVolume(IReadOnlyList<string> sources, string destination)
    {
        try
        {
            var target = Path.GetPathRoot(Path.GetFullPath(destination));

            return sources.All(s => string.Equals(
                Path.GetPathRoot(Path.GetFullPath(s)), target, PathRules.Comparison));
        }
        catch (Exception ex) when (ex is IOException or ArgumentException or NotSupportedException)
        {
            return false;
        }
    }

    private static bool IsLink(string path)
    {
        try
        {
            return (File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0;
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    /// <summary>
    /// Reproduces a link rather than what it points at.
    ///
    /// A directory link is reproduced as a junction, via
    /// <see cref="Native.CreateJunction"/>, because that is the one form an
    /// ordinary user can create — Directory.CreateSymbolicLink needs Developer
    /// Mode and would make copying a folder containing a junction fail on a
    /// stock machine. A relative target cannot be expressed as a junction, and
    /// a symbolic link with one was made by someone who held the privilege and
    /// therefore still holds it, so that case goes the BCL route.
    /// </summary>
    private static void CopyLink(string source, string target)
    {
        FileSystemInfo info = Directory.Exists(source)
            ? new DirectoryInfo(source)
            : new FileInfo(source);

        var points = info.LinkTarget ?? throw new IOException(
            $"'{PathRules.LeafName(source)}' is a reparse point with no readable target.");

        if (info is not DirectoryInfo || !Path.IsPathFullyQualified(points))
        {
            if (info is DirectoryInfo) Directory.CreateSymbolicLink(target, points);
            else File.CreateSymbolicLink(target, points);
            return;
        }

        Directory.CreateDirectory(target);

        try
        {
            Native.CreateJunction(target, points);
        }
        catch (IOException)
        {
            // Leave nothing half-made behind before trying the other route.
            Directory.Delete(target);
            Directory.CreateSymbolicLink(target, points);
        }
    }

    /// <summary>
    /// Removes the link and never what is behind it, which is the whole reason
    /// <see cref="Descend"/> refuses to walk through one.
    /// </summary>
    private static void DeleteLink(string path)
    {
        if (Directory.Exists(path)) Directory.Delete(path);
        else File.Delete(path);
    }

    /// <summary>
    /// Every entry beneath <paramref name="root"/>, parents before their
    /// children, with reparse points reported as leaves.
    ///
    /// **A junction is not a subdirectory.** SearchOption.AllDirectories walks
    /// straight through one, and the three ways that goes wrong are all
    /// reachable from an ordinary folder: a copy silently duplicates whatever
    /// tree the link points at, a move then deletes the originals out of that
    /// tree, and a junction resolving back to an ancestor never terminates at
    /// all. WindowsSearchProvider and WindowsPropertiesProvider already refuse
    /// to follow them, the latter noting that "a junction can point at an
    /// ancestor, and following one turns a measurement into a loop".
    ///
    /// Parent-before-child is relied on twice over: descendants are planned
    /// after the ancestor whose conflict resolution they inherit, and the
    /// source cleanup walks the same order backwards to empty a tree from the
    /// bottom up.
    /// </summary>
    /// <summary>
    /// Walks a tree for the plan, recording what it could not read.
    ///
    /// **An unreadable folder used to end the whole operation**, thrown from
    /// during planning before a single file had been copied — one protected
    /// directory anywhere under the selection and nothing happened at all. The
    /// Linux twin had the opposite fault: it swallowed and carried on, so the
    /// plan was silently short and the copy reported success having quietly
    /// left files behind. Neither told anyone.
    ///
    /// Now it skips and REPORTS, which is the only honest answer: the rest of
    /// the tree really can be copied, and the person has to learn which part
    /// could not be.
    /// </summary>
    internal static IEnumerable<(string Path, ItemKind Kind, long Length)> Descend(
        string root, CancellationToken ct, List<(string Path, Exception Error)>? unreadable = null)
    {
        var pending = new Stack<string>();
        pending.Push(root);

        while (pending.Count > 0)
        {
            ct.ThrowIfCancellationRequested();

            var folder = pending.Pop();

            IEnumerable<FileSystemInfo> children;

            try
            {
                children = new DirectoryInfo(folder).EnumerateFileSystemInfos();
            }
            catch (Exception e) when (e is IOException or UnauthorizedAccessException)
            {
                unreadable?.Add((folder, e));
                continue;
            }

            foreach (var entry in children)
            {
                if ((entry.Attributes & FileAttributes.ReparsePoint) != 0)
                {
                    yield return (entry.FullName, ItemKind.Link, 0);
                }
                else if ((entry.Attributes & FileAttributes.Directory) != 0)
                {
                    yield return (entry.FullName, ItemKind.Directory, 0);
                    pending.Push(entry.FullName);
                }
                else
                {
                    yield return (entry.FullName, ItemKind.File, ((FileInfo)entry).Length);
                }
            }
        }
    }

    /// <summary>
    /// **Takes each root WITH the place it is going**, rather than a
    /// destination folder to derive it from. On a first pass the caller derives
    /// that the same way this used to; on a retry it is whatever the run that
    /// failed had settled on, after Keep both and the redirect map have had
    /// their say. Deriving it here a second time is how a retry would land in
    /// the folder the user asked to keep separate.
    /// </summary>
    private static List<PlannedItem> BuildPlan(
        IReadOnlyList<(string Source, string Target)> roots, CancellationToken ct,
        List<(string Path, Exception Error)>? unreadable = null)
    {
        var plan = new List<PlannedItem>();

        foreach (var (source, target) in roots)
        {
            ct.ThrowIfCancellationRequested();
            var full = Path.GetFullPath(source);

            // Before the directory test, because a junction answers to both.
            if (IsLink(full))
            {
                plan.Add(new PlannedItem(full, target, 0, ItemKind.Link, IsRoot: true));
            }
            else if (Directory.Exists(full))
            {
                plan.Add(new PlannedItem(full, target, 0, ItemKind.Directory, IsRoot: true));

                foreach (var (path, kind, length) in Descend(full, ct, unreadable))
                    plan.Add(new PlannedItem(
                        path, Path.Combine(target, Path.GetRelativePath(full, path)),
                        length, kind, IsRoot: false));
            }
            else if (File.Exists(full))
            {
                plan.Add(new PlannedItem(
                    full, target, new FileInfo(full).Length, ItemKind.File, IsRoot: true));
            }
        }

        return plan;
    }

    /// <summary>
    /// Whether this item can be moved by renaming it rather than rewritten.
    ///
    /// Pulled out so the rule can be tested directly: it is one boolean that
    /// decides between an instant operation and one that reads and writes every
    /// byte, and it is invisible from the outside — both paths produce the same
    /// files.
    /// </summary>
    internal static bool CanRename(string source, string target, bool move)
        => move && Volumes.Same(source, target);

    /// <summary>
    /// Removes a partly-written target after a failed or cancelled copy.
    ///
    /// Swallows everything: this runs while another exception is on its way up,
    /// and a failure to tidy must not replace the reason the copy failed with a
    /// less useful one.
    /// </summary>
    private static void Discard(string target)
    {
        try
        {
            if (File.Exists(target))
            {
                ClearReadOnly(target);
                File.Delete(target);
            }
        }
        catch (Exception ex)
        {
            Vaktari.Core.Quiet.Swallowed("file-ops", ex);
        }
    }

    private static async Task CopyFileAsync(string source, string target, OperationHandle handle)
    {
        var buffer = new byte[BufferSize];

        try
        {
            // Scoped so both handles are closed before the metadata is applied:
            // a timestamp set on an open file is overwritten when the stream
            // flushes.
            await using (var input = new FileStream(
                source, FileMode.Open, FileAccess.Read, FileShare.Read, BufferSize, useAsync: true))
            await using (var output = new FileStream(
                target, FileMode.Create, FileAccess.Write, FileShare.None, BufferSize, useAsync: true))
            {
                int read;
                while ((read = await input.ReadAsync(buffer, handle.Token).ConfigureAwait(false)) > 0)
                {
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);
                    await output.WriteAsync(buffer.AsMemory(0, read), handle.Token).ConfigureAwait(false);
                    handle.BytesCopied(read);
                }
            }
        }
        catch
        {
            // **A half-written file must not be left under the final name.**
            // The target is opened Create, so it exists and is truncated from
            // the first byte — cancel a copy of a large file and what was left
            // behind looked like the file, opened, and was silently incomplete.
            // Worse on Replace: the original was already gone.
            Discard(target);
            throw;
        }

        FileMetadata.Carry(source, target);
    }

    internal enum ItemKind { File, Directory, Link }

    /// <summary>
    /// <paramref name="IsRoot"/> marks one of the paths the user actually
    /// selected, as opposed to something found underneath one. Only those are
    /// worth recording as landing sites: the undo works per selection, not per
    /// file.
    /// </summary>
    private readonly record struct PlannedItem(
        string Source, string Target, long Length, ItemKind Kind, bool IsRoot);

    /// <summary>
    /// Something that can be put back.
    ///
    /// **Undoing returns what would redo it**, rather than redo being a second
    /// list kept in step by hand. Each of these already knows its own inverse —
    /// a rename back is a rename, a move back is a move with the pair the other
    /// way round — so asking the action itself is the one place that cannot
    /// drift out of agreement with what was actually done.
    ///
    /// Null where there is no honest inverse. Restoring something from the bin
    /// is the case: putting it back would mean trashing it again, and the
    /// original trash entry is gone, so the redo would not be the same act.
    /// </summary>
    private interface IUndoable
    {
        ValueTask<IUndoable?> UndoAsync(CancellationToken ct);

        /// <summary>What this would take back, for the menu row and the status
        /// line. Named by the action itself for the same reason its inverse is:
        /// it is the one place that cannot drift out of agreement with what was
        /// actually done.</summary>
        string Describe { get; }
    }


    /// <summary>
    /// Undoing a copy, by sending what arrived to the bin.
    ///
    /// **Copies were not undoable at all**, and the reason given was a good
    /// one: undoing a copy means removing files, and an undo that deletes is
    /// not a safe default. Pasting into the wrong folder is one of the easiest
    /// mistakes a file manager lets you make, though, and Ctrl+Z doing nothing
    /// at all is its own kind of unsafe — the files stay where they should not
    /// be, and the person has to find and remove them by hand.
    ///
    /// The bin is what settles it. Explorer undoes a copy the same way, and
    /// nothing is destroyed: what the undo takes away is sitting in the bin,
    /// recoverable, exactly like anything else deleted from the listing.
    ///
    /// Only what this operation actually created, and only if it is still
    /// there — a copy that landed on top of something the user then edited is
    /// not this operation's to remove.
    /// </summary>
    private sealed class UndoCopy(
        Func<IReadOnlyList<string>, IOperationHandle> trash,
        IReadOnlyList<string> landed) : IUndoable
    {
        public string Describe => UndoNames.Of("copy", landed);

        public async ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            var here = landed
                .Where(path => File.Exists(path) || Directory.Exists(path))
                .ToList();

            if (here.Count == 0) return null;

            await trash(here).Completion.ConfigureAwait(false);

            // No redo. Copying again would be a new act against sources that
            // may have moved on, and the honest way back is the bin.
            return null;
        }
    }

    /// <summary>
    /// Undoing the creation of a folder, a file or a template, the same way —
    /// into the bin.
    ///
    /// New folder, new file and new-from-template all went straight to the
    /// filesystem without passing through this layer, so none of them could be
    /// taken back: Ctrl+Z immediately after Ctrl+Shift+N did nothing.
    /// </summary>
    private sealed class UndoCreate(
        Func<IReadOnlyList<string>, IOperationHandle> trash,
        string created) : IUndoable
    {
        // "creating" rather than "create of": this one reads as a thing that
        // happened rather than as a batch, because it always is exactly one.
        public string Describe => "creating " + PathRules.LeafName(created);

        public async ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            if (!File.Exists(created) && !Directory.Exists(created)) return null;

            await trash([created]).Completion.ConfigureAwait(false);

            return null;
        }
    }

    private sealed class UndoRename(string current, string original) : IUndoable
    {
        // Named by where it is NOW, which is the name on screen — the one the
        // person is looking at when they wonder what Ctrl+Z will do.
        public string Describe => UndoNames.Of("rename", [current]);

        public ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            if (Directory.Exists(current)) RenameDirectory(current, original);
            else if (File.Exists(current)) File.Move(current, original, overwrite: false);
            else return ValueTask.FromResult<IUndoable?>(null);

            // The same rename, the other way round.
            return ValueTask.FromResult<IUndoable?>(new UndoRename(original, current));
        }
    }

    /// <summary>
    /// Takes where things landed rather than where they were sent.
    ///
    /// Reconstructing the landing site as destination + name is wrong the
    /// moment a conflict was resolved: after KeepBoth on `readme.txt` into a
    /// folder that already had one, that arithmetic names the file that was
    /// already there — so the undo moved a bystander back to the source and
    /// left the user's own file sitting under `readme - Copy.txt`.
    /// </summary>
    private sealed class UndoMove(
        IReadOnlyList<(string Source, string Target)> moved) : IUndoable
    {
        public string Describe => UndoNames.Of("move", [.. moved.Select(m => m.Target)]);

        public ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            var undone = new List<(string Source, string Target)>();

            foreach (var (source, landed) in moved)
            {

                if (File.Exists(landed))
                {
                    // File.Move copes with a different volume; Directory.Move
                    // does not, which is why the two are not one call.
                    File.Move(landed, source, overwrite: false);
                }
                else if (Directory.Exists(landed))
                {
                    MoveDirectory(landed, source);
                }
                else
                {
                    // Gone since the move — deleted, or moved again by hand.
                    // Redoing it would move something that is not there.
                    continue;
                }

                undone.Add((landed, source));
            }

            // The pairs the other way round: what was put back goes forward.
            return ValueTask.FromResult<IUndoable?>(
                undone.Count > 0 ? new UndoMove(undone) : null);
        }

        private static void MoveDirectory(string from, string to)
        {
            if (!Directory.Exists(to)
                && string.Equals(Path.GetPathRoot(from), Path.GetPathRoot(to),
                                 StringComparison.OrdinalIgnoreCase))
            {
                Directory.Move(from, to);
                return;
            }

            // Across volumes, or back onto a folder still standing because
            // something inside it was skipped, by hand. Directory.Move throws
            // IOException rather than falling back in either case, and an undo
            // that reports failure after the move succeeded is worse than doing
            // the copy.
            Directory.CreateDirectory(to);

            foreach (var (path, kind, _) in Descend(from, ct: CancellationToken.None))
            {
                var target = Path.Combine(to, Path.GetRelativePath(from, path));

                switch (kind)
                {
                    case ItemKind.Directory: Directory.CreateDirectory(target); break;
                    case ItemKind.Link: CopyLink(path, target); break;
                    default: File.Copy(path, target, overwrite: true); break;
                }
            }

            ClearReadOnlyTree(from);
            Directory.Delete(from, recursive: true);
        }
    }
}
