using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using Vaktari.Core.FileSystem;

namespace Vaktari.Windows;

/// <summary>
/// Copy, move, delete and rename for Windows. Everything destructive routes
/// through here so there is exactly one place to get right.
///
/// <see cref="Trash"/> recycles, via SHFileOperation — see its own note for why
/// that P/Invoke rather than the modern COM IFileOperation.
///
/// **This header used to say ITrashMaintenance was still null**, so there was
/// no Trash view and no Restore and the bin could only be reached from
/// Explorer. WindowsTrashMaintenance shipped and made every word of that false,
/// and nobody came back to delete it — which is how Ctrl+Z after a delete stayed
/// broken here while working on Linux, with a comment explaining why it could
/// not possibly work.
///
/// **<see cref="Delete"/> is never a stand-in for <see cref="Trash"/>.** There
/// is no BCL API for the Recycle Bin, and the tempting shortcut when the
/// P/Invoke looks like work is to delete instead. Deleting a file the user
/// asked to be able to get back is not a degraded version of trashing it; it is
/// the one outcome the trash exists to prevent. When the recycle route refuses,
/// it reports a failure the UI can show, and the user still has their file.
/// </summary>
public sealed class WindowsFileOperations : IFileOperations
{
    private const int BufferSize = 1 << 20;

    private readonly ConcurrentStack<IUndoable> _undo = new();
    private readonly ConcurrentStack<IUndoable> _redo = new();

    public bool CanUndo => !_undo.IsEmpty;

    public IOperationHandle Copy(
        IReadOnlyList<string> sources, string destination,
        Func<FileConflict, ValueTask<ConflictResolution>> onConflict)
        => Run(sources, destination, onConflict, move: false);

    public IOperationHandle Move(
        IReadOnlyList<string> sources, string destination,
        Func<FileConflict, ValueTask<ConflictResolution>> onConflict)
        => Run(sources, destination, onConflict, move: true);

    /// <summary>
    /// Reads the bin, so a recycle can be undone.
    ///
    /// **Injected rather than constructed here** so the undo can be tested
    /// without recycling anything on the machine running the tests.
    /// </summary>
    internal ITrashMaintenance? Bin { get; init; }

    /// <summary>
    /// Stands in for the recycle itself.
    ///
    /// **So the tests do not fill the developer's Recycle Bin.** Everything
    /// worth testing here — which items the undo remembers, what happens when
    /// the bin cannot be read — is about the bookkeeping around
    /// SHFileOperation, not the call, and a test suite that genuinely recycles
    /// leaves litter on the machine that ran it. Returns false to stand for the
    /// user declining the nuke warning.
    /// </summary>
    internal Func<IReadOnlyList<string>, bool>? RecycleOverride { get; init; }

    /// <summary>
    /// The Recycle Bin, via SHFileOperation.
    ///
    /// **SHFileOperation rather than IFileOperation**, which is the supported
    /// modern route and is COM. WINDOWS.md §6 warns that COM under NativeAOT is
    /// the risky combination and needs source-generated interop or it fails at
    /// runtime rather than at build time. This call is one struct and one
    /// function, source-generated by `LibraryImport` and AOT-clean today.
    /// IFileOperation buys progress and collision UI we do not use here, since
    /// <see cref="OperationHandle"/> already reports progress.
    ///
    /// **FOF_WANTNUKEWARNING is load-bearing, not decoration.** With
    /// FOF_ALLOWUNDO alone, a file too large for the bin — or any file when the
    /// bin is disabled for that drive — is *permanently deleted*, silently,
    /// because FOF_NOCONFIRMATION suppressed the question Explorer would have
    /// asked. WANTNUKEWARNING partially overrides NOCONFIRMATION for exactly
    /// that case: ordinary recycling stays silent, and destruction still has to
    /// be agreed to. Removing it turns this method into <see cref="Delete"/>
    /// without saying so.
    /// </summary>
    public IOperationHandle Trash(IReadOnlyList<string> paths)
    {
        var handle = new OperationHandle();

        _ = Task.Run(() =>
        {
            nint from = 0;

            // **Noted before the recycle, so the undo can find what moved.**
            // SHFileOperation reports nothing about what it recycled, which is
            // why this was undoable on Linux and not here. The bin knows,
            // though: a recycled item appears in the listing with the path it
            // came from, so the difference between the listing before and after
            // names exactly what just went in.
            var bin = Bin;
            var before = Snapshot(bin);

            try
            {
                handle.Begin(paths.Count, totalBytes: 0);

                // SHFileOperation wants absolute paths — a relative one is
                // resolved against the process's working directory, which is
                // not the folder being listed.
                var full = paths.Select(Path.GetFullPath).ToList();

                if (RecycleOverride is { } fake)
                {
                    if (!fake(full))
                    {
                        handle.Cancelled();
                        return;
                    }

                    for (var i = 0; i < paths.Count; i++) handle.ItemFinished();

                    var faked = Arrivals(bin, before);
                    if (faked.Count > 0) Remember(new UndoTrash(bin!, faked));

                    handle.Complete();
                    return;
                }

                from = Native.DoubleNullTerminated(full);

                var operation = new Native.SHFILEOPSTRUCTW
                {
                    wFunc = Native.FO_DELETE,
                    pFrom = from,
                    fFlags = Native.FOF_ALLOWUNDO
                           | Native.FOF_NOCONFIRMATION
                           | Native.FOF_WANTNUKEWARNING
                           | Native.FOF_SILENT
                           | Native.FOF_NOERRORUI,
                };

                var status = Native.SHFileOperation(ref operation);

                // Aborted covers the user declining the nuke warning, which is
                // a cancellation rather than a failure — nothing was deleted and
                // nothing went wrong.
                if (operation.fAnyOperationsAborted != 0)
                {
                    handle.Cancelled();
                    return;
                }

                if (status != 0)
                {
                    handle.Failed(new IOException(
                        $"The Recycle Bin refused the operation (SHFileOperation returned {status})."));
                    return;
                }

                // One SHFileOperation covers the whole batch, so there is no
                // per-item progress to report along the way — but the count the
                // handle was opened with still has to be reached, or trashing
                // three files finishes reading "1/3".
                for (var i = 0; i < paths.Count; i++) handle.ItemFinished();

                // What the bin gained is what we just put in it.
                var landed = Arrivals(bin, before);

                if (landed.Count > 0) Remember(new UndoTrash(bin!, landed));

                handle.Complete();
            }
            catch (Exception ex)
            {
                handle.Failed(ex);
            }
            finally
            {
                if (from != 0) Marshal.FreeHGlobal(from);
            }
        });

        return handle;
    }

    /// <summary>
    /// The trash names currently in the bin, or null when there is no bin to
    /// ask — which is how the undo stays absent rather than wrong.
    /// </summary>
    private static HashSet<string>? Snapshot(ITrashMaintenance? bin)
    {
        if (bin is null) return null;

        try
        {
            return bin.List().Select(item => item.TrashName).ToHashSet(StringComparer.Ordinal);
        }
        catch (Exception ex)
        {
            // A bin that will not answer means no undo entry, never a failed
            // delete: the files really did go where the user asked.
            Vaktari.Core.Quiet.Swallowed("file-ops", ex);
            return null;
        }
    }

    /// <summary>
    /// What appeared in the bin since the snapshot.
    ///
    /// **By difference, not by matching original paths.** Matching on where an
    /// item came from picks the wrong entry when the same name has been deleted
    /// before — and deleting, restoring and deleting again is exactly when
    /// somebody reaches for undo. A trash name is unique and new ones can only
    /// be what just arrived.
    /// </summary>
    private static List<string> Arrivals(ITrashMaintenance? bin, HashSet<string>? before)
    {
        if (bin is null || before is null) return [];

        try
        {
            return bin.List()
                .Select(item => item.TrashName)
                .Where(name => !before.Contains(name))
                .ToList();
        }
        catch (Exception ex)
        {
            Vaktari.Core.Quiet.Swallowed("file-ops", ex);
            return [];
        }
    }

    /// <summary>
    /// Puts recycled items back where they came from.
    ///
    /// **This was impossible until the bin could be read.** The comment that
    /// stood here said restoring needed a COM decision that was still
    /// outstanding — WindowsTrashMaintenance shipped and made that false, and
    /// nothing came back to remove the claim. So Ctrl+Z after a delete did
    /// nothing on Windows while working on Linux, with no sign of why.
    /// </summary>
    private sealed class UndoTrash(ITrashMaintenance bin, List<string> trashNames) : IUndoable
    {
        public ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            foreach (var name in trashNames)
            {
                ct.ThrowIfCancellationRequested();

                try
                {
                    bin.Restore(name);
                }
                catch (Exception ex)
                {
                    // One item that will not come back must not strand the
                    // rest — the same rule the copy engine now follows.
                    Vaktari.Core.Quiet.Swallowed("file-ops", ex);
                }
            }

            // No redo: putting them back in the bin would need the paths they
            // were restored to, and Restore reports where each one went. That
            // is the next increment, not a guess made here.
            return ValueTask.FromResult<IUndoable?>(null);
        }
    }

    /// <summary>
    /// Irreversible. Only ever reached from an explicit, separate user action —
    /// never as the default for the Delete key.
    /// </summary>
    public IOperationHandle Delete(IReadOnlyList<string> paths)
    {
        var handle = new OperationHandle();

        _ = Task.Run(async () =>
        {
            try
            {
                handle.Begin(paths.Count, totalBytes: 0);

                foreach (var path in paths)
                {
                    handle.Token.ThrowIfCancellationRequested();
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);

                    handle.ItemStarted(path);

                    // A read-only file refuses to delete on Windows where it
                    // would go on Linux, because the permission is on the file
                    // rather than its directory. The user asked for it to go.
                    //
                    // The whole tree, not just its root: Directory.Delete stops
                    // at the first read-only file inside and throws, leaving
                    // half of what the user asked to remove standing. One
                    // cloned repository is enough to hit that — git writes its
                    // pack files read-only.
                    ClearReadOnlyTree(path);

                    if (Directory.Exists(path)) Directory.Delete(path, recursive: true);
                    else File.Delete(path);

                    handle.ItemFinished();
                }

                handle.Complete();
            }
            catch (OperationCanceledException) { handle.Cancelled(); }
            catch (Exception ex) { handle.Failed(ex); }
        });

        return handle;
    }

    private static void ClearReadOnly(string path)
    {
        try
        {
            var attributes = File.GetAttributes(path);
            if ((attributes & FileAttributes.ReadOnly) != 0)
                File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            // Let the delete itself report the problem.
        }
    }

    /// <summary>
    /// The same, for everything a recursive delete is about to touch. Reparse
    /// points are cleared but not descended through, for the reason
    /// <see cref="Descend"/> gives — and the delete removes the link rather
    /// than what is behind it, so what is behind it is not its business.
    /// </summary>
    /// <summary>
    /// Internal so the Recycle Bin's own purge uses this rather than growing a
    /// second copy. One rule in one place: a duplicate that drifts is how the
    /// bin came to half-destroy read-only payloads while this path handled them
    /// correctly.
    /// </summary>
    internal static void ClearReadOnlyTree(string path)
    {
        ClearReadOnly(path);

        if (!Directory.Exists(path) || IsLink(path)) return;

        foreach (var (entry, _, _) in Descend(path, CancellationToken.None))
            ClearReadOnly(entry);
    }

    public ValueTask RenameAsync(string path, string newName, CancellationToken ct)
    {
        // **Every character Windows refuses, not just the separators.** A
        // colon used to reach the filesystem and come back as the raw "The
        // parameter is incorrect."; worse, "d:notes" is drive-RELATIVE, so
        // Path.Combine discarded the folder and the file silently left the
        // listing for the current directory of drive D:.
        if (FileNames.Refuse(newName) is { } why)
            throw new ArgumentException(why, nameof(newName));

        var directory = PathRules.Parent(Path.GetFullPath(path))
            ?? throw new IOException("A drive root cannot be renamed.");

        var target = Path.Combine(directory, newName);

        // Ordinal, deliberately, where the rest of this file compares paths with
        // PathRules.Same. Same is case-insensitive on Windows, so it calls
        // "readme.txt" and "README.txt" one name and returns here without
        // renaming anything — silently swallowing the exact correction the
        // check below is written to let through.
        if (string.Equals(target, path, StringComparison.Ordinal))
            return ValueTask.CompletedTask;

        // Case-insensitively, so renaming "readme" to "README" is not rejected
        // as already existing — it is the same file, and the rename is exactly
        // how a user fixes the case of a name.
        if ((File.Exists(target) || Directory.Exists(target))
            && !string.Equals(target, path, StringComparison.OrdinalIgnoreCase))
            throw new IOException($"'{newName}' already exists here.");

        if (Directory.Exists(path)) RenameDirectory(path, target);
        else File.Move(path, target, overwrite: false);

        // Before the undo entry, so a rename that is immediately undone leaves
        // the index where it started rather than one step behind.

        Remember(new UndoRename(target, path));
        return ValueTask.CompletedTask;
    }

    /// <summary>
    /// Directory.Move, plus the case-only rename it will not do.
    ///
    /// It compares its two paths case-insensitively on Windows and throws
    /// "source and destination path must be different" when they match, so
    /// fixing the case of a folder name has to go through a staging name — the
    /// two-step Explorer performs on your behalf. Files need none of this:
    /// File.Move hands the pair straight to MoveFileEx, which renames in place.
    /// </summary>
    private static void RenameDirectory(string from, string to)
    {
        if (!string.Equals(from, to, StringComparison.OrdinalIgnoreCase))
        {
            Directory.Move(from, to);
            return;
        }

        var parent = PathRules.Parent(to)
            ?? throw new IOException("A drive root cannot be renamed.");

        string staging;
        do
        {
            staging = Path.Combine(parent, $".vaktari-rename-{Guid.NewGuid():N}");
        }
        while (Directory.Exists(staging) || File.Exists(staging));

        Directory.Move(from, staging);

        try
        {
            Directory.Move(staging, to);
        }
        catch
        {
            // Never leave the folder sitting under the staging name: the user
            // would be looking for it by either of the two names they know.
            Directory.Move(staging, from);
            throw;
        }
    }

    /// <summary>
    /// Records something new, and abandons the redo history.
    ///
    /// **Every application with an undo does this.** Once the history has been
    /// departed from, a redo would apply to a state that no longer exists — it
    /// would move a file that has since been renamed, or put back something
    /// that was overwritten in the meantime.
    /// </summary>
    private void Remember(IUndoable action)
    {
        _redo.Clear();
        _undo.Push(action);
    }

    public bool CanRedo => !_redo.IsEmpty;

    /// <summary>
    /// Puts back what an undo took away.
    ///
    /// The stack is emptied by any new operation, which is what every
    /// application with an undo does: once the history has been departed from,
    /// a redo would apply to a state that no longer exists.
    /// </summary>
    public async ValueTask RedoAsync(CancellationToken ct)
    {
        if (!_redo.TryPop(out var action)) return;

        if (await action.UndoAsync(ct).ConfigureAwait(false) is { } undo) _undo.Push(undo);
    }

    public async ValueTask UndoAsync(CancellationToken ct)
    {
        if (_undo.TryPop(out var action)
            && await action.UndoAsync(ct).ConfigureAwait(false) is { } redo)
            _redo.Push(redo);
    }

    private IOperationHandle Run(
        IReadOnlyList<string> sources, string destination,
        Func<FileConflict, ValueTask<ConflictResolution>> onConflict, bool move)
    {
        var handle = new OperationHandle();

        _ = Task.Run(async () =>
        {
            try
            {
                // Enumerating first means the progress bar is honest from the
                // start rather than discovering the total as it goes.
                var plan = BuildPlan(sources, destination, handle.Token);
                handle.Begin(plan.Count, plan.Sum(p => p.Length));

                // A folder resolved with KeepBoth lands under a name the plan
                // did not know about, and every item beneath it was planned
                // against the old one. Without carrying the change down, the
                // new folder is created empty while the tree merges into the
                // one the user asked to keep separate — which on a move is the
                // source disappearing into it.
                var redirects = new List<(string From, string To)>();

                // Where each top-level source actually ended up, and what was
                // left behind. The undo used to reconstruct the landing site as
                // destination + name, which is only true when nothing was
                // deduplicated or skipped.
                var landings = new List<(string Source, string Target)>();
                var skipped = new List<(string Source, string Target)>();

                foreach (var item in plan)
                {
                    handle.Token.ThrowIfCancellationRequested();
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);

                    var target = Redirect(item.Target, redirects);

                    // **Pasting into the folder it already lives in.** The
                    // target then IS the source, so the conflict prompt could
                    // only offer to replace a file with itself — and Replace
                    // cannot work, because the copy opens the same path for
                    // reading and writing and the error blames "something else
                    // has that file open". Explorer makes a duplicate, which is
                    // plainly what was meant; a MOVE to where it already is has
                    // nothing to do at all.
                    if (PathRules.Same(item.Source, target))
                    {
                        if (move)
                        {
                            handle.ItemFinished();
                            continue;
                        }

                        target = Deduplicate(target, item.Kind == ItemKind.Directory);
                    }

                    if (File.Exists(target) || Directory.Exists(target))
                    {
                        switch (await onConflict(new FileConflict(item.Source, target)).ConfigureAwait(false))
                        {
                            case ConflictResolution.Skip:
                                skipped.Add((item.Source, target));
                                handle.ItemFinished();
                                continue;
                            case ConflictResolution.KeepBoth:
                                var kept = Deduplicate(
                                    target, item.Kind == ItemKind.Directory);
                                if (item.Kind == ItemKind.Directory)
                                    redirects.Add((target, kept));
                                target = kept;
                                break;
                            case ConflictResolution.Cancel:
                                throw new OperationCanceledException();
                            case ConflictResolution.Overwrite:
                                break;
                        }
                    }

                    handle.ItemStarted(item.Source);

                    // **One item's failure is not the batch's.** This whole
                    // block used to sit inside a single try around the entire
                    // loop, so copying twelve files with the third open in
                    // another program copied two and abandoned nine — and said
                    // neither which file nor what was left undone. Cancellation
                    // still ends everything, because that is what was asked for.
                    try
                    {
                    Directory.CreateDirectory(PathRules.Parent(target) ?? destination);

                    switch (item.Kind)
                    {
                        case ItemKind.Directory:
                            Directory.CreateDirectory(target);
                            break;

                        case ItemKind.Link:
                            CopyLink(item.Source, target);
                            if (move) DeleteLink(item.Source);
                            break;

                        default:
                            // **A move within one volume is a rename.** Copying
                            // every byte and deleting the original is correct
                            // and ruinously slow: moving a folder of video
                            // inside one drive rewrote the whole folder. The
                            // giveaway that the trick was already known is that
                            // UNDOING a move has always used File.Move, so the
                            // undo of a fifty-gigabyte move was instant while
                            // the move itself was not.
                            if (CanRename(item.Source, target, move))
                            {
                                // The target only exists here if the user chose
                                // to overwrite it; Skip continued, and KeepBoth
                                // already moved the name aside.
                                if (File.Exists(target)) ClearReadOnly(target);

                                File.Move(item.Source, target, overwrite: true);

                                // Reported so the bar still advances: a rename
                                // moves the bytes without reading any, and a
                                // progress bar that sits at zero through the
                                // fast path looks like a hang.
                                handle.BytesCopied(item.Length);
                            }
                            else
                            {
                                await CopyFileAsync(item.Source, target, handle)
                                    .ConfigureAwait(false);

                                if (move)
                                {
                                    ClearReadOnly(item.Source);
                                    File.Delete(item.Source);
                                }
                            }
                            break;
                    }

                    if (item.IsRoot) landings.Add((item.Source, target));
                    }
                    catch (OperationCanceledException)
                    {
                        // Cancelling means stop, so this one does leave the loop.
                        throw;
                    }
                    catch (Exception ex)
                    {
                        // Recorded and carried on. A directory that could not be
                        // created also means its contents will fail, and each of
                        // those is reported on its own — noisy, but honest, and
                        // far better than nine files silently not arriving.
                        handle.ItemFailed(item.Source, ex);
                    }

                    handle.ItemFinished();
                }

                // Directories are removed only after their contents moved, so a
                // cancelled move never deletes a folder it has not emptied.
                // Every directory the plan touched, deepest first — checking
                // the top-level sources alone left the whole skeleton standing,
                // because a root is never empty while its own subdirectories
                // are still in it.
                if (move)
                {
                    foreach (var directory in plan
                                 .Where(i => i.Kind == ItemKind.Directory)
                                 .Select(i => i.Source)
                                 .Reverse())
                        if (Directory.Exists(directory)
                            && !Directory.EnumerateFileSystemEntries(directory).Any())
                            Directory.Delete(directory);
                }

                // Copies are not undoable: undoing one means deleting files,
                // and an undo that deletes is not a safe default.
                if (move && landings.Count > 0)
                    Remember(new UndoMove(landings));

                handle.Complete();
            }
            catch (OperationCanceledException) { handle.Cancelled(); }
            catch (Exception ex) { handle.Failed(ex); }
        });

        return handle;
    }

    /// <summary>
    /// **Windows' convention, not freedesktop's.** XdgTrash.Deduplicate produces
    /// "file (1).txt"; Explorer produces "file - Copy.txt" and then
    /// "file - Copy (2).txt". WINDOWS.md flagged this as the one place a
    /// platform helper was misleadingly named — the rule differs, so the code
    /// does too rather than being shared.
    /// </summary>
    internal static string Deduplicate(string target, bool isDirectory = false)
    {
        var directory = PathRules.Parent(target);
        if (directory is null) return target;

        // See PathRules.SplitLeaf for why a folder - and a dotfile - is atomic.
        var (stem, extension) = PathRules.SplitLeaf(PathRules.LeafName(target), isDirectory);

        var candidate = Path.Combine(directory, $"{stem} - Copy{extension}");

        for (var n = 2; File.Exists(candidate) || Directory.Exists(candidate); n++)
            candidate = Path.Combine(directory, $"{stem} - Copy ({n}){extension}");

        return candidate;
    }

    /// <summary>
    /// Carries a renamed ancestor down to the descendants planned against its
    /// old name. Applied in order, so a redirect recorded later is already
    /// expressed in terms of the ones before it and nesting composes.
    /// </summary>
    private static string Redirect(string target, List<(string From, string To)> redirects)
    {
        foreach (var (from, to) in redirects)
        {
            if (string.Equals(target, from, PathRules.Comparison)) return to;

            var prefix = from + Path.DirectorySeparatorChar;
            if (target.StartsWith(prefix, PathRules.Comparison))
                target = to + target[from.Length..];
        }

        return target;
    }

    private static bool IsLink(string path)
    {
        try
        {
            return (File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0;
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    /// <summary>
    /// Reproduces a link rather than what it points at.
    ///
    /// A directory link is reproduced as a junction, via
    /// <see cref="Native.CreateJunction"/>, because that is the one form an
    /// ordinary user can create — Directory.CreateSymbolicLink needs Developer
    /// Mode and would make copying a folder containing a junction fail on a
    /// stock machine. A relative target cannot be expressed as a junction, and
    /// a symbolic link with one was made by someone who held the privilege and
    /// therefore still holds it, so that case goes the BCL route.
    /// </summary>
    private static void CopyLink(string source, string target)
    {
        FileSystemInfo info = Directory.Exists(source)
            ? new DirectoryInfo(source)
            : new FileInfo(source);

        var points = info.LinkTarget ?? throw new IOException(
            $"'{PathRules.LeafName(source)}' is a reparse point with no readable target.");

        if (info is not DirectoryInfo || !Path.IsPathFullyQualified(points))
        {
            if (info is DirectoryInfo) Directory.CreateSymbolicLink(target, points);
            else File.CreateSymbolicLink(target, points);
            return;
        }

        Directory.CreateDirectory(target);

        try
        {
            Native.CreateJunction(target, points);
        }
        catch (IOException)
        {
            // Leave nothing half-made behind before trying the other route.
            Directory.Delete(target);
            Directory.CreateSymbolicLink(target, points);
        }
    }

    /// <summary>
    /// Removes the link and never what is behind it, which is the whole reason
    /// <see cref="Descend"/> refuses to walk through one.
    /// </summary>
    private static void DeleteLink(string path)
    {
        if (Directory.Exists(path)) Directory.Delete(path);
        else File.Delete(path);
    }

    /// <summary>
    /// Every entry beneath <paramref name="root"/>, parents before their
    /// children, with reparse points reported as leaves.
    ///
    /// **A junction is not a subdirectory.** SearchOption.AllDirectories walks
    /// straight through one, and the three ways that goes wrong are all
    /// reachable from an ordinary folder: a copy silently duplicates whatever
    /// tree the link points at, a move then deletes the originals out of that
    /// tree, and a junction resolving back to an ancestor never terminates at
    /// all. WindowsSearchProvider and WindowsPropertiesProvider already refuse
    /// to follow them, the latter noting that "a junction can point at an
    /// ancestor, and following one turns a measurement into a loop".
    ///
    /// Parent-before-child is relied on twice over: descendants are planned
    /// after the ancestor whose conflict resolution they inherit, and the
    /// source cleanup walks the same order backwards to empty a tree from the
    /// bottom up.
    /// </summary>
    private static IEnumerable<(string Path, ItemKind Kind, long Length)> Descend(
        string root, CancellationToken ct)
    {
        var pending = new Stack<string>();
        pending.Push(root);

        while (pending.Count > 0)
        {
            ct.ThrowIfCancellationRequested();

            foreach (var entry in new DirectoryInfo(pending.Pop()).EnumerateFileSystemInfos())
            {
                if ((entry.Attributes & FileAttributes.ReparsePoint) != 0)
                {
                    yield return (entry.FullName, ItemKind.Link, 0);
                }
                else if ((entry.Attributes & FileAttributes.Directory) != 0)
                {
                    yield return (entry.FullName, ItemKind.Directory, 0);
                    pending.Push(entry.FullName);
                }
                else
                {
                    yield return (entry.FullName, ItemKind.File, ((FileInfo)entry).Length);
                }
            }
        }
    }

    private static List<PlannedItem> BuildPlan(
        IReadOnlyList<string> sources, string destination, CancellationToken ct)
    {
        var plan = new List<PlannedItem>();

        foreach (var source in sources)
        {
            ct.ThrowIfCancellationRequested();
            var full = Path.GetFullPath(source);
            var name = PathRules.LeafName(full);

            // Before the directory test, because a junction answers to both.
            if (IsLink(full))
            {
                plan.Add(new PlannedItem(
                    full, Path.Combine(destination, name), 0, ItemKind.Link, IsRoot: true));
            }
            else if (Directory.Exists(full))
            {
                var root = Path.Combine(destination, name);
                plan.Add(new PlannedItem(full, root, 0, ItemKind.Directory, IsRoot: true));

                foreach (var (path, kind, length) in Descend(full, ct))
                    plan.Add(new PlannedItem(
                        path, Path.Combine(root, Path.GetRelativePath(full, path)),
                        length, kind, IsRoot: false));
            }
            else if (File.Exists(full))
            {
                plan.Add(new PlannedItem(
                    full, Path.Combine(destination, name),
                    new FileInfo(full).Length, ItemKind.File, IsRoot: true));
            }
        }

        return plan;
    }

    /// <summary>
    /// Whether this item can be moved by renaming it rather than rewritten.
    ///
    /// Pulled out so the rule can be tested directly: it is one boolean that
    /// decides between an instant operation and one that reads and writes every
    /// byte, and it is invisible from the outside — both paths produce the same
    /// files.
    /// </summary>
    internal static bool CanRename(string source, string target, bool move)
        => move && Volumes.Same(source, target);

    /// <summary>
    /// Removes a partly-written target after a failed or cancelled copy.
    ///
    /// Swallows everything: this runs while another exception is on its way up,
    /// and a failure to tidy must not replace the reason the copy failed with a
    /// less useful one.
    /// </summary>
    private static void Discard(string target)
    {
        try
        {
            if (File.Exists(target))
            {
                ClearReadOnly(target);
                File.Delete(target);
            }
        }
        catch (Exception ex)
        {
            Vaktari.Core.Quiet.Swallowed("file-ops", ex);
        }
    }

    private static async Task CopyFileAsync(string source, string target, OperationHandle handle)
    {
        var buffer = new byte[BufferSize];

        try
        {
            // Scoped so both handles are closed before the metadata is applied:
            // a timestamp set on an open file is overwritten when the stream
            // flushes.
            await using (var input = new FileStream(
                source, FileMode.Open, FileAccess.Read, FileShare.Read, BufferSize, useAsync: true))
            await using (var output = new FileStream(
                target, FileMode.Create, FileAccess.Write, FileShare.None, BufferSize, useAsync: true))
            {
                int read;
                while ((read = await input.ReadAsync(buffer, handle.Token).ConfigureAwait(false)) > 0)
                {
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);
                    await output.WriteAsync(buffer.AsMemory(0, read), handle.Token).ConfigureAwait(false);
                    handle.BytesCopied(read);
                }
            }
        }
        catch
        {
            // **A half-written file must not be left under the final name.**
            // The target is opened Create, so it exists and is truncated from
            // the first byte — cancel a copy of a large file and what was left
            // behind looked like the file, opened, and was silently incomplete.
            // Worse on Replace: the original was already gone.
            Discard(target);
            throw;
        }

        FileMetadata.Carry(source, target);
    }

    private enum ItemKind { File, Directory, Link }

    /// <summary>
    /// <paramref name="IsRoot"/> marks one of the paths the user actually
    /// selected, as opposed to something found underneath one. Only those are
    /// worth recording as landing sites: the undo works per selection, not per
    /// file.
    /// </summary>
    private readonly record struct PlannedItem(
        string Source, string Target, long Length, ItemKind Kind, bool IsRoot);

    /// <summary>
    /// Something that can be put back.
    ///
    /// **Undoing returns what would redo it**, rather than redo being a second
    /// list kept in step by hand. Each of these already knows its own inverse —
    /// a rename back is a rename, a move back is a move with the pair the other
    /// way round — so asking the action itself is the one place that cannot
    /// drift out of agreement with what was actually done.
    ///
    /// Null where there is no honest inverse. Restoring something from the bin
    /// is the case: putting it back would mean trashing it again, and the
    /// original trash entry is gone, so the redo would not be the same act.
    /// </summary>
    private interface IUndoable
    {
        ValueTask<IUndoable?> UndoAsync(CancellationToken ct);
    }

    private sealed class UndoRename(string current, string original) : IUndoable
    {
        public ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            if (Directory.Exists(current)) RenameDirectory(current, original);
            else if (File.Exists(current)) File.Move(current, original, overwrite: false);
            else return ValueTask.FromResult<IUndoable?>(null);

            // The same rename, the other way round.
            return ValueTask.FromResult<IUndoable?>(new UndoRename(original, current));
        }
    }

    /// <summary>
    /// Takes where things landed rather than where they were sent.
    ///
    /// Reconstructing the landing site as destination + name is wrong the
    /// moment a conflict was resolved: after KeepBoth on `readme.txt` into a
    /// folder that already had one, that arithmetic names the file that was
    /// already there — so the undo moved a bystander back to the source and
    /// left the user's own file sitting under `readme - Copy.txt`.
    /// </summary>
    private sealed class UndoMove(
        IReadOnlyList<(string Source, string Target)> moved) : IUndoable
    {
        public ValueTask<IUndoable?> UndoAsync(CancellationToken ct)
        {
            var undone = new List<(string Source, string Target)>();

            foreach (var (source, landed) in moved)
            {

                if (File.Exists(landed))
                {
                    // File.Move copes with a different volume; Directory.Move
                    // does not, which is why the two are not one call.
                    File.Move(landed, source, overwrite: false);
                }
                else if (Directory.Exists(landed))
                {
                    MoveDirectory(landed, source);
                }
                else
                {
                    // Gone since the move — deleted, or moved again by hand.
                    // Redoing it would move something that is not there.
                    continue;
                }

                undone.Add((landed, source));
            }

            // The pairs the other way round: what was put back goes forward.
            return ValueTask.FromResult<IUndoable?>(
                undone.Count > 0 ? new UndoMove(undone) : null);
        }

        private static void MoveDirectory(string from, string to)
        {
            if (!Directory.Exists(to)
                && string.Equals(Path.GetPathRoot(from), Path.GetPathRoot(to),
                                 StringComparison.OrdinalIgnoreCase))
            {
                Directory.Move(from, to);
                return;
            }

            // Across volumes, or back onto a folder still standing because
            // something inside it was skipped, by hand. Directory.Move throws
            // IOException rather than falling back in either case, and an undo
            // that reports failure after the move succeeded is worse than doing
            // the copy.
            Directory.CreateDirectory(to);

            foreach (var (path, kind, _) in Descend(from, ct: CancellationToken.None))
            {
                var target = Path.Combine(to, Path.GetRelativePath(from, path));

                switch (kind)
                {
                    case ItemKind.Directory: Directory.CreateDirectory(target); break;
                    case ItemKind.Link: CopyLink(path, target); break;
                    default: File.Copy(path, target, overwrite: true); break;
                }
            }

            ClearReadOnlyTree(from);
            Directory.Delete(from, recursive: true);
        }
    }
}
