using Vaktari.Linux;
using Xunit;

namespace Vaktari.Linux.Tests;

/// <summary>
/// What "Open with" does with an application the person has taken away.
///
/// **Un-choosing an application moved it down the menu instead of off it.**
/// mimeapps.list was read for [Removed Associations] and mimeinfo.cache was
/// then appended unfiltered, so the very entry the removal named came back in
/// as an ordinary association — one row lower than before, and still there.
///
/// The cache is generated by the desktop from the .desktop files themselves and
/// records only what each application CLAIMS it can open. It knows nothing about
/// anybody's choices, which is why the spec puts it below every mimeapps.list
/// and why every removal those files made has to reach it.
///
/// Built from synthetic directories under a temp root rather than from this
/// machine: the type is one no installed application claims, so the answer is
/// the same on a developer's Linux box, on CI and on Windows.
/// </summary>
public sealed class RemovedAssociationsTests : IDisposable
{
    private const string Mime = "application/x-vaktari-removed-test";

    private readonly string _root = Path.Combine(
        Path.GetTempPath(), "vaktari-removed-" + Guid.NewGuid().ToString("N")[..8]);

    private readonly Func<string, bool, string>? _sniffBefore = DesktopEntries.SniffOverride;
    private readonly Dictionary<string, string?> _envBefore = [];

    public RemovedAssociationsTests()
    {
        var apps = Path.Combine(_root, "share", "applications");
        var config = Path.Combine(_root, "config");
        var empty = Path.Combine(_root, "empty");

        Directory.CreateDirectory(apps);
        Directory.CreateDirectory(config);
        Directory.CreateDirectory(empty);

        Desktop(Path.Combine(apps, "keep.desktop"), "Keeper");
        Desktop(Path.Combine(apps, "gone.desktop"), "Unchosen");

        // Both applications claim the type, which is all the cache ever says.
        File.WriteAllText(
            Path.Combine(apps, "mimeinfo.cache"),
            $"[MIME Cache]{Environment.NewLine}{Mime}=keep.desktop;gone.desktop;{Environment.NewLine}");

        // And the person has said no to one of them.
        File.WriteAllText(
            Path.Combine(config, "mimeapps.list"),
            $"[Removed Associations]{Environment.NewLine}{Mime}=gone.desktop;{Environment.NewLine}");

        // Every root the walk consults, pointed somewhere known: the machine
        // running this must not be able to add or remove a row.
        Env("XDG_DATA_HOME", Path.Combine(_root, "share"));
        Env("XDG_DATA_DIRS", empty);
        Env("XDG_CONFIG_HOME", config);
        Env("XDG_CONFIG_DIRS", empty);
        Env("XDG_CURRENT_DESKTOP", null);

        // The type comes from the sniff: a name with no extension is what the
        // glob database cannot answer, so nothing on this machine decides it.
        DesktopEntries.SniffOverride = (_, _) => Mime;
    }

    public void Dispose()
    {
        DesktopEntries.SniffOverride = _sniffBefore;

        foreach (var (name, value) in _envBefore)
            Environment.SetEnvironmentVariable(name, value);

        try { Directory.Delete(_root, recursive: true); }
        catch (Exception) { /* a temp dir is not worth failing over */ }

        GC.SuppressFinalize(this);
    }

    private void Env(string name, string? value)
    {
        _envBefore[name] = Environment.GetEnvironmentVariable(name);
        Environment.SetEnvironmentVariable(name, value);
    }

    private static void Desktop(string path, string name)
        => File.WriteAllText(
            path,
            string.Join(
                Environment.NewLine,
                "[Desktop Entry]", "Type=Application", $"Name={name}", "Exec=/bin/true", ""));

    private static List<string> Offered()
        => [.. DesktopEntries.ForFile(Path.Combine(Path.GetTempPath(), "a-file-with-no-extension"))
                 .Select(o => o.Name)];

    /// <summary>
    /// **The removal reaches the cache.** Before this, gone.desktop was offered
    /// anyway, because the cache was appended without consulting the removals
    /// the mimeapps.list walk had just gathered.
    /// </summary>
    [Fact]
    public void An_application_taken_away_is_not_offered_by_the_cache()
        => Assert.DoesNotContain("Unchosen", Offered());

    /// <summary>
    /// The control, so an empty menu cannot pass the test above: the other
    /// application in the same cache line, which nothing removed, IS offered.
    /// </summary>
    [Fact]
    public void And_the_one_beside_it_still_is()
        => Assert.Equal(["Keeper"], Offered());
}
